// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemm.proto

package com;

public final class Gemm {
  private Gemm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatrixOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zmqsample.Matrix)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    boolean hasDimensionX();
    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    int getDimensionX();

    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    boolean hasDimensionY();
    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    int getDimensionY();

    /**
     * <code>repeated float element = 3;</code>
     */
    java.util.List<java.lang.Float> getElementList();
    /**
     * <code>repeated float element = 3;</code>
     */
    int getElementCount();
    /**
     * <code>repeated float element = 3;</code>
     */
    float getElement(int index);
  }
  /**
   * Protobuf type {@code com.zmqsample.Matrix}
   */
  public static final class Matrix extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.zmqsample.Matrix)
      MatrixOrBuilder {
    // Use Matrix.newBuilder() to construct.
    private Matrix(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Matrix(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Matrix defaultInstance;
    public static Matrix getDefaultInstance() {
      return defaultInstance;
    }

    public Matrix getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Matrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dimensionX_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dimensionY_ = input.readInt32();
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                element_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              element_.add(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                element_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                element_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          element_ = java.util.Collections.unmodifiableList(element_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.Gemm.internal_static_com_zmqsample_Matrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.Gemm.internal_static_com_zmqsample_Matrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.Gemm.Matrix.class, com.Gemm.Matrix.Builder.class);
    }

    public static com.google.protobuf.Parser<Matrix> PARSER =
        new com.google.protobuf.AbstractParser<Matrix>() {
      public Matrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Matrix(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Matrix> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DIMENSIONX_FIELD_NUMBER = 1;
    private int dimensionX_;
    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    public boolean hasDimensionX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    public int getDimensionX() {
      return dimensionX_;
    }

    public static final int DIMENSIONY_FIELD_NUMBER = 2;
    private int dimensionY_;
    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    public boolean hasDimensionY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    public int getDimensionY() {
      return dimensionY_;
    }

    public static final int ELEMENT_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Float> element_;
    /**
     * <code>repeated float element = 3;</code>
     */
    public java.util.List<java.lang.Float>
        getElementList() {
      return element_;
    }
    /**
     * <code>repeated float element = 3;</code>
     */
    public int getElementCount() {
      return element_.size();
    }
    /**
     * <code>repeated float element = 3;</code>
     */
    public float getElement(int index) {
      return element_.get(index);
    }

    private void initFields() {
      dimensionX_ = 0;
      dimensionY_ = 0;
      element_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDimensionX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDimensionY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, dimensionX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, dimensionY_);
      }
      for (int i = 0; i < element_.size(); i++) {
        output.writeFloat(3, element_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dimensionX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dimensionY_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getElementList().size();
        size += dataSize;
        size += 1 * getElementList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.Gemm.Matrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Gemm.Matrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Gemm.Matrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Gemm.Matrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Gemm.Matrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.Gemm.Matrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.Gemm.Matrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.Gemm.Matrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.Gemm.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.Gemm.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.Gemm.Matrix prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zmqsample.Matrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zmqsample.Matrix)
        com.Gemm.MatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.Gemm.internal_static_com_zmqsample_Matrix_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.Gemm.internal_static_com_zmqsample_Matrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.Gemm.Matrix.class, com.Gemm.Matrix.Builder.class);
      }

      // Construct using com.Gemm.Matrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dimensionX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dimensionY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.Gemm.internal_static_com_zmqsample_Matrix_descriptor;
      }

      public com.Gemm.Matrix getDefaultInstanceForType() {
        return com.Gemm.Matrix.getDefaultInstance();
      }

      public com.Gemm.Matrix build() {
        com.Gemm.Matrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.Gemm.Matrix buildPartial() {
        com.Gemm.Matrix result = new com.Gemm.Matrix(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dimensionX_ = dimensionX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dimensionY_ = dimensionY_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          element_ = java.util.Collections.unmodifiableList(element_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.element_ = element_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.Gemm.Matrix) {
          return mergeFrom((com.Gemm.Matrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.Gemm.Matrix other) {
        if (other == com.Gemm.Matrix.getDefaultInstance()) return this;
        if (other.hasDimensionX()) {
          setDimensionX(other.getDimensionX());
        }
        if (other.hasDimensionY()) {
          setDimensionY(other.getDimensionY());
        }
        if (!other.element_.isEmpty()) {
          if (element_.isEmpty()) {
            element_ = other.element_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureElementIsMutable();
            element_.addAll(other.element_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDimensionX()) {
          
          return false;
        }
        if (!hasDimensionY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.Gemm.Matrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.Gemm.Matrix) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dimensionX_ ;
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public boolean hasDimensionX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public int getDimensionX() {
        return dimensionX_;
      }
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public Builder setDimensionX(int value) {
        bitField0_ |= 0x00000001;
        dimensionX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public Builder clearDimensionX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dimensionX_ = 0;
        onChanged();
        return this;
      }

      private int dimensionY_ ;
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public boolean hasDimensionY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public int getDimensionY() {
        return dimensionY_;
      }
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public Builder setDimensionY(int value) {
        bitField0_ |= 0x00000002;
        dimensionY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public Builder clearDimensionY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dimensionY_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> element_ = java.util.Collections.emptyList();
      private void ensureElementIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          element_ = new java.util.ArrayList<java.lang.Float>(element_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public java.util.List<java.lang.Float>
          getElementList() {
        return java.util.Collections.unmodifiableList(element_);
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public int getElementCount() {
        return element_.size();
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public float getElement(int index) {
        return element_.get(index);
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder setElement(
          int index, float value) {
        ensureElementIsMutable();
        element_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder addElement(float value) {
        ensureElementIsMutable();
        element_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder addAllElement(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureElementIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, element_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder clearElement() {
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zmqsample.Matrix)
    }

    static {
      defaultInstance = new Matrix(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zmqsample.Matrix)
  }

  public interface MatrixGemmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zmqsample.MatrixGemm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    boolean hasMatrixA();
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    com.Gemm.Matrix getMatrixA();
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    com.Gemm.MatrixOrBuilder getMatrixAOrBuilder();

    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    boolean hasMatrixB();
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    com.Gemm.Matrix getMatrixB();
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    com.Gemm.MatrixOrBuilder getMatrixBOrBuilder();
  }
  /**
   * Protobuf type {@code com.zmqsample.MatrixGemm}
   */
  public static final class MatrixGemm extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.zmqsample.MatrixGemm)
      MatrixGemmOrBuilder {
    // Use MatrixGemm.newBuilder() to construct.
    private MatrixGemm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatrixGemm(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatrixGemm defaultInstance;
    public static MatrixGemm getDefaultInstance() {
      return defaultInstance;
    }

    public MatrixGemm getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatrixGemm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.Gemm.Matrix.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = matrixA_.toBuilder();
              }
              matrixA_ = input.readMessage(com.Gemm.Matrix.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(matrixA_);
                matrixA_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.Gemm.Matrix.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = matrixB_.toBuilder();
              }
              matrixB_ = input.readMessage(com.Gemm.Matrix.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(matrixB_);
                matrixB_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.Gemm.internal_static_com_zmqsample_MatrixGemm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.Gemm.internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.Gemm.MatrixGemm.class, com.Gemm.MatrixGemm.Builder.class);
    }

    public static com.google.protobuf.Parser<MatrixGemm> PARSER =
        new com.google.protobuf.AbstractParser<MatrixGemm>() {
      public MatrixGemm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatrixGemm(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatrixGemm> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MATRIXA_FIELD_NUMBER = 1;
    private com.Gemm.Matrix matrixA_;
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    public boolean hasMatrixA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    public com.Gemm.Matrix getMatrixA() {
      return matrixA_;
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    public com.Gemm.MatrixOrBuilder getMatrixAOrBuilder() {
      return matrixA_;
    }

    public static final int MATRIXB_FIELD_NUMBER = 2;
    private com.Gemm.Matrix matrixB_;
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    public boolean hasMatrixB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    public com.Gemm.Matrix getMatrixB() {
      return matrixB_;
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    public com.Gemm.MatrixOrBuilder getMatrixBOrBuilder() {
      return matrixB_;
    }

    private void initFields() {
      matrixA_ = com.Gemm.Matrix.getDefaultInstance();
      matrixB_ = com.Gemm.Matrix.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMatrixA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMatrixB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMatrixA().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMatrixB().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, matrixA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, matrixB_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, matrixA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, matrixB_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Gemm.MatrixGemm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Gemm.MatrixGemm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Gemm.MatrixGemm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.Gemm.MatrixGemm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.Gemm.MatrixGemm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.Gemm.MatrixGemm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.Gemm.MatrixGemm prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zmqsample.MatrixGemm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zmqsample.MatrixGemm)
        com.Gemm.MatrixGemmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.Gemm.internal_static_com_zmqsample_MatrixGemm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.Gemm.internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.Gemm.MatrixGemm.class, com.Gemm.MatrixGemm.Builder.class);
      }

      // Construct using com.Gemm.MatrixGemm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMatrixAFieldBuilder();
          getMatrixBFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (matrixABuilder_ == null) {
          matrixA_ = com.Gemm.Matrix.getDefaultInstance();
        } else {
          matrixABuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (matrixBBuilder_ == null) {
          matrixB_ = com.Gemm.Matrix.getDefaultInstance();
        } else {
          matrixBBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.Gemm.internal_static_com_zmqsample_MatrixGemm_descriptor;
      }

      public com.Gemm.MatrixGemm getDefaultInstanceForType() {
        return com.Gemm.MatrixGemm.getDefaultInstance();
      }

      public com.Gemm.MatrixGemm build() {
        com.Gemm.MatrixGemm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.Gemm.MatrixGemm buildPartial() {
        com.Gemm.MatrixGemm result = new com.Gemm.MatrixGemm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (matrixABuilder_ == null) {
          result.matrixA_ = matrixA_;
        } else {
          result.matrixA_ = matrixABuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (matrixBBuilder_ == null) {
          result.matrixB_ = matrixB_;
        } else {
          result.matrixB_ = matrixBBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.Gemm.MatrixGemm) {
          return mergeFrom((com.Gemm.MatrixGemm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.Gemm.MatrixGemm other) {
        if (other == com.Gemm.MatrixGemm.getDefaultInstance()) return this;
        if (other.hasMatrixA()) {
          mergeMatrixA(other.getMatrixA());
        }
        if (other.hasMatrixB()) {
          mergeMatrixB(other.getMatrixB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMatrixA()) {
          
          return false;
        }
        if (!hasMatrixB()) {
          
          return false;
        }
        if (!getMatrixA().isInitialized()) {
          
          return false;
        }
        if (!getMatrixB().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.Gemm.MatrixGemm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.Gemm.MatrixGemm) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.Gemm.Matrix matrixA_ = com.Gemm.Matrix.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.Gemm.Matrix, com.Gemm.Matrix.Builder, com.Gemm.MatrixOrBuilder> matrixABuilder_;
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public boolean hasMatrixA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public com.Gemm.Matrix getMatrixA() {
        if (matrixABuilder_ == null) {
          return matrixA_;
        } else {
          return matrixABuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder setMatrixA(com.Gemm.Matrix value) {
        if (matrixABuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matrixA_ = value;
          onChanged();
        } else {
          matrixABuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder setMatrixA(
          com.Gemm.Matrix.Builder builderForValue) {
        if (matrixABuilder_ == null) {
          matrixA_ = builderForValue.build();
          onChanged();
        } else {
          matrixABuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder mergeMatrixA(com.Gemm.Matrix value) {
        if (matrixABuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              matrixA_ != com.Gemm.Matrix.getDefaultInstance()) {
            matrixA_ =
              com.Gemm.Matrix.newBuilder(matrixA_).mergeFrom(value).buildPartial();
          } else {
            matrixA_ = value;
          }
          onChanged();
        } else {
          matrixABuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder clearMatrixA() {
        if (matrixABuilder_ == null) {
          matrixA_ = com.Gemm.Matrix.getDefaultInstance();
          onChanged();
        } else {
          matrixABuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public com.Gemm.Matrix.Builder getMatrixABuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMatrixAFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public com.Gemm.MatrixOrBuilder getMatrixAOrBuilder() {
        if (matrixABuilder_ != null) {
          return matrixABuilder_.getMessageOrBuilder();
        } else {
          return matrixA_;
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.Gemm.Matrix, com.Gemm.Matrix.Builder, com.Gemm.MatrixOrBuilder> 
          getMatrixAFieldBuilder() {
        if (matrixABuilder_ == null) {
          matrixABuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.Gemm.Matrix, com.Gemm.Matrix.Builder, com.Gemm.MatrixOrBuilder>(
                  getMatrixA(),
                  getParentForChildren(),
                  isClean());
          matrixA_ = null;
        }
        return matrixABuilder_;
      }

      private com.Gemm.Matrix matrixB_ = com.Gemm.Matrix.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.Gemm.Matrix, com.Gemm.Matrix.Builder, com.Gemm.MatrixOrBuilder> matrixBBuilder_;
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public boolean hasMatrixB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public com.Gemm.Matrix getMatrixB() {
        if (matrixBBuilder_ == null) {
          return matrixB_;
        } else {
          return matrixBBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder setMatrixB(com.Gemm.Matrix value) {
        if (matrixBBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matrixB_ = value;
          onChanged();
        } else {
          matrixBBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder setMatrixB(
          com.Gemm.Matrix.Builder builderForValue) {
        if (matrixBBuilder_ == null) {
          matrixB_ = builderForValue.build();
          onChanged();
        } else {
          matrixBBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder mergeMatrixB(com.Gemm.Matrix value) {
        if (matrixBBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              matrixB_ != com.Gemm.Matrix.getDefaultInstance()) {
            matrixB_ =
              com.Gemm.Matrix.newBuilder(matrixB_).mergeFrom(value).buildPartial();
          } else {
            matrixB_ = value;
          }
          onChanged();
        } else {
          matrixBBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder clearMatrixB() {
        if (matrixBBuilder_ == null) {
          matrixB_ = com.Gemm.Matrix.getDefaultInstance();
          onChanged();
        } else {
          matrixBBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public com.Gemm.Matrix.Builder getMatrixBBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMatrixBFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public com.Gemm.MatrixOrBuilder getMatrixBOrBuilder() {
        if (matrixBBuilder_ != null) {
          return matrixBBuilder_.getMessageOrBuilder();
        } else {
          return matrixB_;
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.Gemm.Matrix, com.Gemm.Matrix.Builder, com.Gemm.MatrixOrBuilder> 
          getMatrixBFieldBuilder() {
        if (matrixBBuilder_ == null) {
          matrixBBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.Gemm.Matrix, com.Gemm.Matrix.Builder, com.Gemm.MatrixOrBuilder>(
                  getMatrixB(),
                  getParentForChildren(),
                  isClean());
          matrixB_ = null;
        }
        return matrixBBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zmqsample.MatrixGemm)
    }

    static {
      defaultInstance = new MatrixGemm(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zmqsample.MatrixGemm)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zmqsample_Matrix_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zmqsample_Matrix_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zmqsample_MatrixGemm_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGemm.proto\022\rcom.zmqsample\"A\n\006Matrix\022\022\n" +
      "\ndimensionX\030\001 \002(\005\022\022\n\ndimensionY\030\002 \002(\005\022\017\n" +
      "\007element\030\003 \003(\002\"\\\n\nMatrixGemm\022&\n\007matrixA\030" +
      "\001 \002(\0132\025.com.zmqsample.Matrix\022&\n\007matrixB\030" +
      "\002 \002(\0132\025.com.zmqsample.MatrixB\013\n\003comB\004Gem" +
      "m"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zmqsample_Matrix_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zmqsample_Matrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_zmqsample_Matrix_descriptor,
        new java.lang.String[] { "DimensionX", "DimensionY", "Element", });
    internal_static_com_zmqsample_MatrixGemm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_zmqsample_MatrixGemm_descriptor,
        new java.lang.String[] { "MatrixA", "MatrixB", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
