/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_pmem_PersistentMemoryPlatform */

#ifndef _Included_org_apache_spark_pmem_PersistentMemoryPlatform
#define _Included_org_apache_spark_pmem_PersistentMemoryPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_pmem_PersistentMemoryPlatform
 * Method:    initializeNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_pmem_PersistentMemoryPlatform_initializeNative
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_apache_spark_pmem_PersistentMemoryPlatform
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_pmem_PersistentMemoryPlatform_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_spark_pmem_PersistentMemoryPlatform
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_pmem_PersistentMemoryPlatform_freeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_spark_pmem_PersistentMemoryPlatform
 * Method:    copyMemory
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_pmem_PersistentMemoryPlatform_copyMemory
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
