/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_unsafe_VMPlatform */

#ifndef _Included_org_apache_spark_unsafe_VMPlatform
#define _Included_org_apache_spark_unsafe_VMPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_unsafe_VMPlatform
 * Method:    initializeNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_unsafe_VMPlatform_initializeNative
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_apache_spark_unsafe_VMPlatform
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_unsafe_VMPlatform_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_spark_unsafe_VMPlatform
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_unsafe_VMPlatform_freeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_spark_unsafe_VMPlatform
 * Method:    copyMemory
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_unsafe_VMPlatform_copyMemory
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
